name: Vite workflow test 2
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cloud: ovh
            endpoint: url1
          - cloud: aws
            endpoint: url2
        vers: [12, 13, 14]
    steps:
      - run: echo ${{ matrix.cloud}} ${{matrix.endpoint}}
