name: Vite workflow test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: actions/checkout@v4
      - name: configure cache
        uses: actions/cache@v3
        with:
          path: ./vite-project/.npm
          key: ${{ runner.os }}-${{ hashFiles('./vite-project/package-lock.json') }}
          restore-keys: |
            ${{ runner.os}}-

      - name: install dependencies
        run: npm ci --cache .npm --prefer-offline
        working-directory: ./vite-project
