name: Mon premier workflow
on: push

jobs:
  testartifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > test.txt
      - uses: actions/upload-artifact@v3
        with:
          name: myfirstartifact
          path: ./test.txt
