name: Mon premier workflow
on: push

jobs:
  testartifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: myfirstartifact
          path: ./test.txt

  downloadartifacts:
    needs: testartifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myfirstartifact
          path: ./ici

      - run: |
          ls
          ls ./ici
          cat ./ici/test.txt
