name: Vite workflow test 2
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.os == 'ubuntu-latest' }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        vers: [12, 13]
        exclude:
          - os: windows-latest
            vers: 12
    steps:
      - run: echo ${{ matrix.os}} ${{matrix.vers}}
